### ISSUE TITLE
выводить ошибку, когда не найдена папка или класс в аргументах dpcli

### ISSUE THREAD

**Issue by kys** [beta-eto-code/bx.data.provider#1]
если запустить из консоли ./dpcli dp:run, но написать неправильный --type или -c, то не выдается никакой ошибки, просто ничего не произойдёт (я писала update вместо updates и долго тупила, почему не работает =) ). выводить ошибку "недопустимый тип" или "класс не найден" при некорректных параметрах

**Comment by alex19pov31** [comment]
реализовано
