### ISSUE TITLE
добавить сортировку вызова классов из папки при исполнении dpcli

### ISSUE THREAD

**Issue by kys** [beta-eto-code/bx.data.provider#2]
чтобы делать зависимую генерацию данных (когда есть привязки по ид одних сущностей к другим), надо запускать генерации в строго определенном порядке, чтобы сначала генерить исходные сущности, а потом уже связанные с ними. 
для импорта и апдейта это тоже критично при наличии связей через внешние ключи в бд. 
добавить какой-то переопределяемый метод для сортировки классов в папках для dpli dp:run

**Comment by alex19pov31** [comment]
реализовано
