### ISSUE TITLE
текст результата не соответствует действию

### ISSUE THREAD

**Issue by kys** [beta-eto-code/bx.data.provider#4]
я запускаю --type=updates, а он говорит
PositionNameRemove: сгенерировано - 10, ошибок генерации - 0
может показаться, что что-то пошло не так, я же не генерацию запускала
предлагаю добавить тип generate отдельно в \BX\Data\Provider\Commands\RunTaskCommand::printResult
а вариант по умолчанию сделать "обработано - N, ошибок обработки - Y"

**Comment by alex19pov31** [comment]
реализовано
